[package]
name = "xgram-utils"

version.workspace = true
description.workspace = true
license.workspace = true
readme = "../../docs/CRATES_README.md"
documentation.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

edition.workspace = true
[lints]
workspace = true

[dependencies]
