unstable_features = true

format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
float_literal_trailing_zero = "Never"
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
trailing_comma = "Never"
use_field_init_shorthand = true
wrap_comments = true
