[package]
name = "xgram-telegram-api"

version.workspace = true
description.workspace = true
license.workspace = true
readme = "../../docs/CRATES_README.md"
documentation.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
xgram-utils.workspace = true

log.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with.workspace = true
smallvec = { workspace = true, features = ["serde"] }
thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["parking_lot"] }
