name: "Push/PR Checks"
on:
  push:
    branches:
      - main
      - dev
  pull_request:
permissions:
  contents: read
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Rust
        run: |
          rustup toolchain install nightly --profile minimal --no-self-update
          rustup component add --toolchain nightly rustfmt clippy
      - name: Rust cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-all-crates: 'true'
      - name: Install Dependencies
        run: cargo install cargo-audit cargo-nextest --locked
      - name: Check formatting
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build
        if: github.ref_name == 'main'
        run: cargo build --release
      - name: Cargo Audit
        run: cargo audit
      - name: Run tests
        run: cargo nextest run --config-file nextest.toml --profile ci
